defaults:
  - dataset: ???
  - model: rnndet
  - _self_

checkpoint: ???
use_test_set: False
hardware:
  num_workers:
    eval: 4
  gpus: 0 # GPU idx (multi-gpu not supported for validation)
batch_size:
  eval: 8
training:
  precision: 16
custom:
  select_sequence: null

wandb:
  wandb_runpath: null # WandB run path. E.g. USERNAME/PROJECTNAME/1grv5kg6
  artifact_name: null # Name of checkpoint/artifact. Required for resuming. E.g. USERNAME/PROJECTNAME/checkpoint-1grv5kg6-last:v15
  artifact_local_file: null # If specified, will use the provided local filepath instead of downloading it. Required if resuming with DDP.
  resume_only_weights: False
  group_name: ??? # Specify group name of the run
  project_name: RVT

logging:
  ckpt_every_n_epochs: 1
  validation:
    high_dim:
      enable: True
      every_n_epochs: 1
      n_samples: 1
